### ISSUE TITLE
Update for unknown module field

### ISSUE THREAD

**Issue by Nisto** [REDasmOrg/REDasm-Signature#1]
Great project - glad I found this repository/wiki as it has helped me a bit. Wanted to contribute back, so thought I'd drop this piece of information:

The currently [unknown field](https://github.com/REDasmOrg/REDasm-Signature/blob/master/psx/psyqlib.cpp#L227) in the module chunk is a 32-bit date/time value. See [reference](https://docs.microsoft.com/en-us/cpp/c-runtime-library/32-bit-windows-time-date-formats?view=vs-2017) on Microsoft's site.

Example to decode it in Python:

```python
date, time = struct.unpack("<HH", buf[off:off+4])

year   = (date & 0b1111111000000000) >> 9
month  = (date & 0b0000000111100000) >> 5
day    = (date & 0b0000000000011111) >> 0
hour   = (time & 0b1111100000000000) >> 11
minute = (time & 0b0000011111100000) >> 5
second = (time & 0b0000000000011111) >> 0

year += 1980 # year is relative to 1980
second *= 2 # seconds are in increments of 2
```

**Comment by Dax89** [comment]
Thanks!
